### ISSUE TITLE
Subscribe to EventStream from multiple brigdes simulaneously

### ISSUE THREAD

**Issue by axeljacobs** [home-assistant-libs/aiohue#107]
Hello,
Sorry not an issue, more a need for help/question.

Is it possible to initialize two (or more) instances of the HueBridgeV2 class and subscribe simultaneously to the EventStream of each instance ?

Thanks

**Comment by marcelveldt** [comment]
Yes this is no problem. Just initialize multiple HueBridgeV2 instances.

**Comment by axeljacobs** [comment]
Thanks for your response. 
I'm starting with Python and async is still complicated/unclear for me.

I'm starting from your example v2_bridge.py, would you be so kind to provide an example...

Thanks for your time
