### ISSUE TITLE
Friends of hue - always short_release before long_release

### ISSUE THREAD

**Issue by DavidDeSloovere** [home-assistant-libs/aiohue#135]
Hello friends,

I've got a wireless [Friend Of Hue switch made by Niko](https://www.niko.eu/nl-be/artikel/154-91004) (green power / enocean), linked to the official bridge, that I want to use in in Home Assistant via the 'device' triggers. We have the 'released after short press' and 'released after long press' trigger. The short press trigger is working fine. But the long press also triggers a long press which makes the automations unreliable (race conditions?). Although it [can be handled](https://community.home-assistant.io/t/friends-of-hue-abb-switch-reporting-two-events-on-long-button-press/268965/3?u=daviddesloovere) with a timeout and extra checks (with a lot of yaml). For most people this is too difficult. 

Is there a way this can be handle in this lib?

I have ran the samples in the project (awesome they are included, I don't know much about python, but got them up and running in minutes).

I'm seeing `'initial_press' > 'repeat' > 'repeat' > 'repeat' > 'short_release' > 'long_release'`

Full log:
```
received event update Button(id='452e5d58-f324-4296-83c1-c0f092992b8a', owner=ResourceIdentifier(rid='daa2555b-1819-4aa9-a918-8cf746040edd', rtype=<ResourceTypes.DEVICE: 'device'>), metadata=ButtonMetadata(control_id=1), button=ButtonFeature(last_event=<ButtonEvent.INITIAL_PRESS: 'initial_press'>), id_v1='/sensors/43', type=<ResourceTypes.BUTTON: 'button'>)


received event update Button(id='452e5d58-f324-4296-83c1-c0f092992b8a', owner=ResourceIdentifier(rid='daa2555b-1819-4aa9-a918-8cf746040edd', rtype=<ResourceTypes.DEVICE: 'device'>), metadata=ButtonMetadata(control_id=1), button=ButtonFeature(last_event=<ButtonEvent.REPEAT: 'repeat'>), id_v1='/sensors/43', type=<ResourceTypes.BUTTON: 'button'>)


received event update Button(id='452e5d58-f324-4296-83c1-c0f092992b8a', owner=ResourceIdentifier(rid='daa2555b-1819-4aa9-a918-8cf746040edd', rtype=<ResourceTypes.DEVICE: 'device'>), metadata=ButtonMetadata(control_id=1), button=ButtonFeature(last_event=<ButtonEvent.REPEAT: 'repeat'>), id_v1='/sensors/43', type=<ResourceTypes.BUTTON: 'button'>)


received event update Button(id='452e5d58-f324-4296-83c1-c0f092992b8a', owner=ResourceIdentifier(rid='daa2555b-1819-4aa9-a918-8cf746040edd', rtype=<ResourceTypes.DEVICE: 'device'>), metadata=ButtonMetadata(control_id=1), button=ButtonFeature(last_event=<ButtonEvent.REPEAT: 'repeat'>), id_v1='/sensors/43', type=<ResourceTypes.BUTTON: 'button'>)


received event update Button(id='452e5d58-f324-4296-83c1-c0f092992b8a', owner=ResourceIdentifier(rid='daa2555b-1819-4aa9-a918-8cf746040edd', rtype=<ResourceTypes.DEVICE: 'device'>), metadata=ButtonMetadata(control_id=1), button=ButtonFeature(last_event=<ButtonEvent.SHORT_RELEASE: 'short_release'>), id_v1='/sensors/43', type=<ResourceTypes.BUTTON: 'button'>)


received event update Button(id='452e5d58-f324-4296-83c1-c0f092992b8a', owner=ResourceIdentifier(rid='daa2555b-1819-4aa9-a918-8cf746040edd', rtype=<ResourceTypes.DEVICE: 'device'>), metadata=ButtonMetadata(control_id=1), button=ButtonFeature(last_event=<ButtonEvent.LONG_RELEASE: 'long_release'>), id_v1='/sensors/43', type=<ResourceTypes.BUTTON: 'button'>)

```

This might not make any sense, but:
Maybe the short_release could be ignored when a 'repeat' is seen. When we get a 'repeat' after 'initial_press', we probably only care about the 'long_release'. Although I don't see the 'long_release' after only 1 'repeat'.

Like I said, I can't write python. But I can help test this.

**Comment by marcelveldt** [comment]
Well, we implemented a workaround (or name it hack) to overcome a limitation in the first place. The Hue bridge doesn't even send any other events but the "initial_press" and "short_release" for these 3rd party remotes. It's something very low on their todo list so we implemented our workaround just as an alternative.

This workaround is layered "on top" of the original logic and I'd like to keep it that way. We just fire additional "fake" repeat events if we did not receive a "short_release" within X seconds and we fire a "long_release" whenever we fired 1 of more repeat events. As simple as that.

Filtering out original events is probably more dangerous, especially if the official support is added later.
This workaround shouldn't be here in the first place but is implemented as a workaround for all those with these remotes. You should probably just adjust your automation and filter out the "short release" before the "long release".

In terms of automations, just have a "wait for" condition.
trigger: initial_press
sequence:
1) wait_for "long_release" max 5 seconds
2) execute your action that needs to run only on long press

**Comment by DavidDeSloovere** [comment]
I can't seem to figure out how to do this with yaml/ui.
I've got the wait_for_trigger. But I don't know how to cancel the automation with the short press. When the long press automation runs, the short also runs, because that event is always fired.

**Comment by marcelveldt** [comment]
Please use the forums for that kind of support. I'll close here as it is not something to fix in this library.

**Comment by KHV8** [comment]
While we wait for signify, I have created a blueprint solving the problem.
https://community.home-assistant.io/t/philips-hue-friends-of-hue-switch-4-buttons-for-hue-integration/499450
