### ISSUE TITLE
Bulbs serial number 

### ISSUE THREAD

**Issue by xeor** [home-assistant-libs/aiohue#139]
Is it possible to expose the bulbs serial numbers as well using aiohue? I don't see that in the model, but I'm not sure if it's even possible to do using the bridge api

**Comment by mvdwetering** [comment]
If you are referring to the 6 digit codes on the lamp, those are not available on the bridge API

**Comment by xeor** [comment]
Yes, correct.. Thanks.. Guess we can just close this one then :)
