### ISSUE TITLE
Value {} of type <class 'dict'> is invalid for RelativeRotary.relative_rotary

### ISSUE THREAD

**Issue by rdeneer** [home-assistant-libs/aiohue#148]
Using the new Hue Tap dial switch gives the following warning in the System Log:

Logger: aiohue.util
Source: runner.py:119
Value {} of type <class 'dict'> is invalid for RelativeRotary.relative_rotary, expected value of type typing.Optional[aiohue.v2.models.relative_rotary.RelativeRotaryFeature]

This warning pops up when rebooting HA, not when actually using the switch itself. Other than that, it is working fine.

**Comment by kwbeck** [comment]
I'm seeing the same, but don't have a Hue Tap dial switch, only Lutron Auroras.

Logger:` aiohue.util
Source: runner.py:119
First occurred: 08:16:24 (1 occurrences)
Last logged: 08:16:24

Value {} of type <class 'dict'> is invalid for RelativeRotary.relative_rotary, expected value of type typing.Optional[aiohue.v2.models.relative_rotary.RelativeRotaryFeature]

**Comment by killtux** [comment]
seeing the same errors in the log. anyone having an idea what causes this?

**Comment by marcelveldt** [comment]
For now ignore it. I will fix it later. It can do no harm. It just means that at the Hue hub sends an initial message out of spec.
