### ISSUE TITLE
Friends of philips hue do not send 1+2 and 3+4 events

### ISSUE THREAD

**Issue by samuolis** [home-assistant-libs/aiohue#183]
At the moment philips hue is not sending 1+2 and 3+4 button press to home assistant. 

I have senic friends of philips hue buttons. When I connect this button with zigbee2mqtt i get these events, but in philips hue integration they are not sending thise events. As I understand in past phillips hue integration had those events, but they were removed. Is it possible to return that? It restricts a lot that it is possible to only have single button presses.

![Screenshot_20230220-225736.png](https://user-images.githubusercontent.com/28056781/220197526-d6f1bb5a-2e61-4239-8e0b-82252071bf3e.png)

**Comment by marcelveldt** [comment]
They are removed from the API by Signify so out of our control. Maybe one day they will bring them back. Look in the official app, if you can assign an action to a button combination there, we should be able to do the same in aiohue/HA as we use the exact same API as the official Hue app.

**Comment by samuolis** [comment]
I can do that in hue essentials app https://www.hueessentials.com/. It looks like it is similar API to Philips hue. Am I wrong? Maybe it would be good to use theirs API if it differs, because it looks like it is similar. @marcelveldt

**Comment by marcelveldt** [comment]
Nope, Hue Essentials is not the Official App and they still use the V1 API which will be phased out.
We have no intention of still utilizing the V1 API and that is also not very helpful towards Signify developers. Better wait for the feature to become available in the current V2 API.

I'm going to close here. If you see this feature in the official Hue app and it still not works in HA, please reopen so we can implement/fix it. Thanks!

**Comment by samuolis** [comment]
@marcelveldt hey is it possible to request this feature anywhere from Signify?
