### ISSUE TITLE
 Hue HDMI Sync Box support

### ISSUE THREAD

**Issue by Jay2645** [home-assistant-libs/aiohue#20]
I got a new Hue HDMI Sync Box, and I'd like for it to be automated through Home Assistant.

The only problem is that there doesn't seem to be any support regarding turning it on or off -- I have a Chromecast with ambient mode enabled, and so outside of something like Home Assistant I have no way of knowing if a movie started.

It'd be nice if there was a way to toggle the Hue Sync functionality for an entertainment center on or off somehow via API.

**Comment by mvdwetering** [comment]
Just bumped into this issue and given the age of the issue you might already found a solution, but in case you did not.
You can find my custom integration for the Philips Hue Play HDMI Sync Box here https://github.com/mvdwetering/huesyncbox

**Comment by marcelveldt** [comment]
Closing this one as the Hue Sync Box uses a different API not related to the Hue api
