### ISSUE TITLE
Philips Hue White GU10 Bluetooth lights report incorrect controlcapabilities["ct"]["max"]

### ISSUE THREAD

**Issue by basnijholt** [home-assistant-libs/aiohue#36]
They report 650, however, when setting them to any number above 454 they fall back to 454 (which is the actual max).

Not sure if this library can do anything about it though? Should I report this to Philips instead?

**Comment by balloob** [comment]
Definitely report it to Philips.

We should also add a guard for it. Not sure if in this lib or in HA.

**Comment by basnijholt** [comment]
On https://www.philips-hue.com/en-sg/p/hue-white-ambiance-single-bulb-gu10/8718696769805 it mentions "Shades of white (2200-6500K)". So 1e6/2200≈454.54.

This problem is quite annoying in https://github.com/home-assistant/core/pull/40626, where it (optionally) detects manual state changes.

**Comment by balloob** [comment]
I guess we can make the change when the property is fetched. https://github.com/home-assistant-libs/aiohue/blob/master/aiohue/lights.py#L71

**Comment by balloob** [comment]
btw, manual state changes should be tracked using `context` ? Most lights will slightly change their target settings when you set it, ie brightness 233 becomes 234 etc.

**Comment by basnijholt** [comment]
> btw, manual state changes should be tracked using context ? 

Yes, that is also what I am doing. However, as an extra option, I track state changes that were made outside of HA. So for example flipping a Hue light on and off with the power switch. These lights changing their color temp back make it seem like such a change (outside of HA) happened).

**Comment by zierbeek** [comment]
is it possible to implement the bluetooth bulbs in HA?
