### ISSUE TITLE
Lutron aurora random event data

### ISSUE THREAD

**Issue by Garulf** [home-assistant-libs/aiohue#56]
I'm attempting to repurpose an Lutron Aurora dial for a new automation. 
However when the dial is rotated (direction doesn't matter) the event data is randomly 1-2 with no consistency.
With no documentation on this and even looking at the code I cant find which action fires which event.

Is this expected behavior, limitation of the API, or a bug?

EDIT: It seems event 1 is triggered by rotating the dial a very small amount, while event 2 is large rotations.
Is there a way to get more meaningful information?

```
{
    "event_type": "hue_event",
    "data": {
        "id": "desk",
        "unique_id": "XX:XX:XX:0f:XX:fe:XX:c1-XX-XXXX-XXXX",
        "event": 2,
        "last_updated": "2021-05-26T09:19:49"
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-26T09:19:49.177680+00:00",
    "context": {
        "id": "XXXXXXXXX",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by balloob** [comment]
The Hue events endpoint works by keeping a request open and feeding it the first event that comes in, then closing the connection. We then have to establish a new connection. There is a timeout of some time between events hence the larger jumps.
