### ISSUE TITLE
Remote API support?

### ISSUE THREAD

**Issue by nullify005** [home-assistant-libs/aiohue#62]
Hey There,

I've been playing with integrating my Hue lights with the Home Assistant, but the integration seems to rely on having local access to the Hue Bridge.

Is there any consideration for using the Remote API at all? or are there any HACS projects (which I haven't found yet) which do function in this manner?

https://developers.meethue.com/develop/hue-api/remote-api-quick-start-guide/

My use case is that my home-assistant is deployed outside my home network in AWS & I really don't want to build an ipsec tunnel between the two just to talk to the bridge.

Regards, Lee

**Comment by balloob** [comment]
Remote API is out of scope for this project or the built-in Home Assistant integration.
