### ISSUE TITLE
Handling of switch power events with new Hue firmware

### ISSUE THREAD

**Issue by spasche** [home-assistant-libs/aiohue#63]
With bridge firmware 1946080020 released on July 19th, power level events are fired on switch sensors.

The problem is that consumers of the API assume that switch events come from button presses and thus they are now seeing "fake" button events when the switch power level changes.

Home Assistant bug: https://github.com/home-assistant/core/issues/53177

**Comment by dennisbrouwer91** [comment]
Just curious, do we have an ETA to get this merged? I would love to have this fixed!

**Comment by spasche** [comment]
If you want to help, you could try the branch in the referenced PR and report if it fixes your issue and if you find other regressions (you would also need this change for Home Assistant: https://github.com/spasche/core/commit/09616407644b3bfbd453a58b095984e63611230d)

**Comment by dennisbrouwer91** [comment]
@spasche I would love to try that, but that is not so easy as I'm running Home-Assistant on HassOS and fully containerized.

**Comment by spasche** [comment]
Yes, I understand that's harder to test in this case. It's easier when running in a Python environment.

**Comment by balloob** [comment]
Will be part of the beta today.
