### ISSUE TITLE
Scene object is missing lightstates

### ISSUE THREAD

**Issue by BenoitAnastay** [home-assistant-libs/aiohue#66]
The hue API endpoint that's linting scenes do not send the `lightstates` value

There should be a way to call `/api/{username}/scenes/{id}` to get them and a function to do a `PUT` on that.

It would help to dynamically update scenes for exemple to fine ajust the switch behavior through the day

**Comment by BenoitAnastay** [comment]
The PR #67 is intended to fix a part of this issue

**Comment by marcelveldt** [comment]
The V2 implementation is now prepared to also update/create existing objects such as scenes.

**Comment by BenoitAnastay** [comment]
Nice, thanks I'll see how to update my custom compoments with that.
